In [1]:
import numpy as np

def sensitivity_matrix(A, dA):
    # Compute the SVD of A
    U, E, Vh = np.linalg.svd(A, full_matrices=True)

    # Perturb A
    Aperturbed = A + dA

    # Compute the SVD of the perturbed matrix
    Up, Ep, Vhp = np.linalg.svd(Aperturbed, full_matrices=True)

    # Calculate the perturbations in U, E, and Vh
    dU = Up - U
    dE = np.diag(Ep - E)
    dVh = Vhp - Vh

    # Compute the sensitivity matrix
    sensitivity_matrix = np.dot(Vh.T, dU) + dE + np.dot(dVh.T, U)

    return sensitivity_matrix

# Create a random square matrix A
A = np.random.rand(3, 3)

# Perturbation matrix dA
dA = 1e-6 * np.random.rand(3, 3)

# Compute the sensitivity matrix
sensitivity_matrix_result = sensitivity_matrix(A, dA)

print("Sensitivity Matrix:")
print(sensitivity_matrix_result)

Sensitivity Matrix:
[[ 1.71379457e-06 -1.18460307e-06 -2.57004532e-08]
 [-3.34582820e-07  1.15844681e-07  1.04843727e-06]
 [ 1.91201335e-07  5.32839925e-08 -1.24976965e-07]]
